name: 'Publish HTML report to Firebase Storage'
description: 'Installs Node.js, pnpm, and project dependencies.'
inputs:
  workload-identity-provider:
    description: 'Workload Identity Provider ID (projects/__/locations/global/workloadIdentityPools/__/providers/__)'
    required: true
  service-account:
    description: 'Service account email (__@__.iam.gserviceaccount.com)'
    required: true
  storage-prefix:
    description: 'Storage bucket name (gs://__)'
    required: true
  path:
    description: 'Path to HTML report'
    required: true
  suffix:
    description: 'Suffix to append to the path'
    default: 'report'
  index:
    description: 'Path to index.html'
    default: 'index.html'
runs:
  using: 'composite'
  steps:
    - name: Authenticate to Google Cloud
      uses: 'google-github-actions/auth@v1'
      with:
        workload_identity_provider: ${{ inputs.workload-identity-provider }}
        service_account: ${{ inputs.service-account }}
    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v1'
    - name: 'Copy HTML report to Firebase Storage'
      shell: bash
      run: |
        GS_URL='${{ inputs.storage-prefix }}/${{ github.repository }}/${{ github.run_id }}/${{ github.run_attempt }}/${{ inputs.suffix }}'
        HTTP_URL="$(echo "$GS_URL" | sed 's/gs:\/\//https:\/\/storage.googleapis.com\//')/${{ inputs.index }}"
        gsutil -m cp -r '${{ inputs.path }}' "$GS_URL"
        echo "[${{ inputs.suffix }}]($HTTP_URL)" >> $GITHUB_STEP_SUMMARY
        echo "http-url=$HTTP_URL" >> $GITHUB_OUTPUT
